version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=admin_cloud
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cloud_db
    ports:
      - "5432:5432"

